name: Deploy to Staging

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Renombrar Dockerfile
        run: cp Dockerfile.staging Dockerfile

      - name: Create .env file
        run: |
          touch .env.staging
          echo "APP_PORT=${{ secrets.APP_PORT }}" >> .env.staging
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env.staging
          echo "ENCRYPT_SALT_ROUNDS=${{ secrets.ENCRYPT_SALT_ROUNDS }}" >> .env.staging
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env.staging
          echo "DEFAULT_USER_PASSWORD=${{ secrets.DEFAULT_USER_PASSWORD }}" >> .env.staging
          echo "PRIVATE_API_SECRET=${{ secrets.PRIVATE_API_SECRET }}" >> .env.staging
          echo "NODE_ENV=staging" >> .env.staging
          cat .env.staging

      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      - name: Deploy to Railway
        env:
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
        run: RAILWAY_TOKEN=${{ secrets.RAILWAY_DEPLOY_TOKEN }} railway up --service=resident-hub-back
